apiVersion: v1
kind: Service
metadata:
  labels:
    app: xs2a-gateway
  name: xs2a-gateway
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8081
  selector:
    app: xs2a-gateway
    deploymentconfig: xs2a-gateway
  sessionAffinity: None
  type: ClusterIP
