server:
  port: 8081

info:
  app:
    name: ${spring.application.name}
    description: "Description"
    version: @project.version@
    artifactId: @project.artifactId@

spring:
  application:
    name: xs2a-gateway
  jackson:
    default-property-inclusion: non_null

logging.level.org.apache.http.wire: DEBUG

one-bank-mode:
  code: set bank code of the bank

---
spring:
  profiles: deutscheBank

one-bank-mode:
  code: 50010517