server:
  port: 8999

spring:
  application:
    name: xs2a-adapter
  jackson:
    default-property-inclusion: non_null

---
spring:
  profiles: dev
logging:
  config: classpath:logback-dev.xml
  level:
    org.apache.http.wire: DEBUG
    com.google.api.client.http: DEBUG
