apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: xs2a-adapter
  name: xs2a-adapter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: xs2a-adapter
    deploymentconfig: xs2a-adapter
  template:
    metadata:
      labels:
        app: xs2a-adapter
        deploymentconfig: xs2a-adapter
    spec:
      {{- if .Values.adapter.customConfig }}
      initContainers:
        - name: xs2a-adapter-config
          image: alpine:latest
          env:
            - name: ADAPTER_CONFIG_DEFAULT_URL
              value: "https://raw.githubusercontent.com/\
                      adorsys/xs2a-adapter/\
                      develop/xs2a-adapter-aspsp-registry/\
                      src/main/resources/aspsp-adapter-config.csv"
            - name: ADAPTER_CONFIG_EXTENSION_URL
              value: "https://git.adorsys.de/api/v4/projects/\
                      1773/repository/files/\
                      data%2Fxs2a-adapter%2F\
                      aspsp%2Dadapter%2Dconfig%2Dextension%2Ecsv\
                      /raw?ref=master"
            - name: ADAPTER_CONFIG_EXTENSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: xs2a-adapter
                  key: gitlab-token
          command: ["/bin/sh", "-c"]
          args:
            - apk add --no-cache curl;
              cd /custom-config;
              wget ${ADAPTER_CONFIG_DEFAULT_URL} -O aspsp-adapter-config-default.csv;
              cat aspsp-adapter-config-default.csv > aspsp-adapter-config.csv;
              curl --request GET --header 'PRIVATE-TOKEN: ${ADAPTER_CONFIG_EXTENSION_TOKEN}' ${ADAPTER_CONFIG_EXTENSION_URL};
              cat aspsp-adapter-config-extension.csv >> aspsp-adapter-config.csv
          volumeMounts:
          - name: xs2a-adapter-config
            mountPath: /custom-config
      {{- end }}
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            {{- if .Values.adapter.customConfig }}
            - name: CSV_ASPSP_ADAPTER_CONFIG_FILE_PATH
              value: /opt/xs2a-adapter/custom-config/aspsp-adapter-config.csv
            {{- end }}
            - name: dkb.token.consumer_key
              valueFrom:
                secretKeyRef:
                  name: dkb-token
                  key: consumer-key
            - name: dkb.token.consumer_secret
              valueFrom:
                secretKeyRef:
                  name: dkb-token
                  key: consumer-secret
            - name: KEY_STORE_TYPE
              valueFrom:
                secretKeyRef:
                  name: qwac-secret
                  key: key-store-type
            - name: KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qwac-secret
                  key: key-store-password
            - name: SSL_OPTS
              value: >-
                -Djavax.net.ssl.keyStoreType=$(KEY_STORE_TYPE)
                -Djavax.net.ssl.keyStore=/qwac/key-store
                -Djavax.net.ssl.keyStorePassword=$(KEY_STORE_PASSWORD)
          imagePullPolicy: Always
          name: xs2a-adapter
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: qwac-secret-volume
              mountPath: /qwac
            {{- if .Values.adapter.customConfig }}
            - name: xs2a-adapter-config
              mountPath: /opt/xs2a-adapter/custom-config
            {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: qwac-secret-volume
          secret:
            secretName: qwac-secret
        {{- if .Values.adapter.customConfig }}
        - name: xs2a-adapter-config
          persistentVolumeClaim:
            claimName: xs2a-adapter-config
        {{- end }}
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - xs2a-adapter
        from:
          kind: ImageStreamTag
          name: xs2a-adapter:{{ .Values.adapter.tag }}
          namespace: {{ .Values.adapter.namespace }}
      type: ImageChange
