name: Develop CI
on:
  push:
    branches:
      - amos-modelbank

env:
  XS2A_ADAPTER_IMAGE_NAME: xs2a-adapter
  XS2A_ADAPTER_IMAGE_TAG: develop
  OPENSHIFT_REGISTRY: openshift-registry.adorsys.de
  OPENSHIFT_NAMESPACE_AMOS_MODELBANK: amos-modelbank

jobs:
  build:
    name: Build project & docker file
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean verify -B

      - name: Build docker image
        env:
          LOCAL_IMAGE_NAME: ${{ env.XS2A_ADAPTER_IMAGE_NAME }}:test
        run: docker build -t ${LOCAL_IMAGE_NAME} .

  deploy:
    name: Deploy docker image to the registry
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean install -B -Dbuild.number=${GITHUB_SHA::7}
        shell: bash

      - name: Build docker image
        env:
          LOCAL_IMAGE_NAME: ${{ env.XS2A_ADAPTER_IMAGE_NAME }}:${{ env.XS2A_ADAPTER_IMAGE_TAG }}
        run: docker build -t ${LOCAL_IMAGE_NAME} .
      
      - name: AMOS_MODELBANK. Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.OPENSHIFT_REGISTRY }}
          username: image-pusher
          password: ${{ secrets.OPENSHIFT_TOKEN_AMOS_MODELBANK }}

      - name: AMOS_MODELBANK. Deploy docker image
        env:
          LOCAL_IMAGE_NAME: ${{ env.XS2A_ADAPTER_IMAGE_NAME }}:${{ env.XS2A_ADAPTER_IMAGE_TAG }}
          OPENSHIFT_IMAGE_NAME: ${{ env.OPENSHIFT_REGISTRY }}/${{ env.OPENSHIFT_NAMESPACE_AMOS_MODELBANK }}/${{ env.XS2A_ADAPTER_IMAGE_NAME }}:${{ env.XS2A_ADAPTER_IMAGE_TAG }}
        run: |
          docker tag ${LOCAL_IMAGE_NAME} ${OPENSHIFT_IMAGE_NAME}
          docker push ${OPENSHIFT_IMAGE_NAME}
